### PR TITLE
Fix- open link in external browser

### PR DESCRIPTION
**Pull request by ToluAkin**
Fix for [issue](https://github.com/SinadShan/PassVault/issues/3) #3

### CODE REVIEW

**Comment by ToluAkin** [comment]
@SinadShan Kindly review. Thank you!

**Comment by SinadShan** [comment]
Thanks for your contribution. This wasn't exactly what was intended, it would be better to open the link in the user's default browser instead of a browserWindow of the app. Perhaps you could take a look at [this](https://www.electronjs.org/docs/api/shell)

**Comment by ToluAkin** [comment]
> Thanks for your contribution. This wasn't exactly what was intended, it would be better to open the link in the user's default browser instead of a browserWindow of the app. Perhaps you could take a look at [this](https://www.electronjs.org/docs/api/shell)

Updating now

**Comment by ToluAkin** [comment]
@SinadShan I got my solution [here](https://www.grzegorowski.com/electron-open-in-new-window)

**Comment by SinadShan** [comment]
Thanks again, but your solution has some problems. You are creating another window apart from the main browserWindow `win` ,and that too not from the main process. Your code should work fine in the main process i.e, `app.js`, but it seems the `shell` API is having some problems with opening the url, similar to this issue [here](https://github.com/electron/electron/issues/16149). So I suggest ditching this method and use [exec](https://stackabuse.com/executing-shell-commands-with-node-js/) to run the shell command `xdg-open https://github.com/SinadShan/PassVault/releases`,  which will open the link in an external browser.

**Pull request closed without merging**
